apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-crt-prod
  namespace: prophecy
spec:
  secretName: prophecy-tls
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
  commonName: unpeumoinsdunkilo.prophecy-eip.com
  dnsNames:
    - unpeumoinsdunkilo.prophecy-eip.com