version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - DB_PORT=5432
      - DB_HOST
      - API_PORT
      - DB_USERNAME=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_USER}
    depends_on:
      - db
    networks:
        - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
    networks:
      - db

networks:
    db:
